# Generated by Django 5.2.10 on 2026-02-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('max_slots', models.IntegerField()),
                ('current_slots_taken', models.IntegerField(default=0)),
                ('registration_deadline', models.DateTimeField()),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.ngo')),
            ],
        ),
    ]
