# Generated by Django 6.0.1 on 2026-03-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('deleted', 'Deleted'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
